### ISSUE TITLE
New GDX for tests

### ISSUE THREAD

**Issue by giannou** [pik-piam/remind2#102]
A new GDX that will be automatically downloaded for testing the library is needed. Should we take a standard SSP2-policy GDX?

**Comment by giannou** [comment]
@pfuehrlich-pik

**Comment by Renato-Rodrigues** [comment]
I guess so, I don't run much H12 runs anymore.
If it would be a 21 regions I would suggest to always get the:
/p/projects/remind/inputdata/CESparametersAndGDX/indu_fixed_shares-buil_simple-tran_complex-POP_pop_SSP2-GDP_gdp_SSP2-Kap_debt_limit-FE_med-Reg_2b1450bc.gdx

**Comment by giannou** [comment]
ok done

**Comment by fschreyer** [comment]
We should definitely get a policy GDX because otherwise we won't check a couple of summations e.g. referring to carbon management, gross/net emissions etc.

**Comment by Renato-Rodrigues** [comment]
ops, you are right. an calibration one is not good enough.

**Comment by pfuehrlich-pik** [comment]
How about this one: `/p/projects/remind/modeltests/output/SSP2-AMT-PkBudg900_2021-08-28_02.46.53/fulldata.gdx` @fschreyer ?

**Comment by pfuehrlich-pik** [comment]
Or this with 21 regions? How do you know what regions were used?

**Comment by fschreyer** [comment]
This GDX looks good. It has CDR and CCU. 

> Or this with 21 regions? How do you know what regions were used?

You see it in the definition of the ``all_regi`` set.

**Comment by giannou** [comment]
ok I uploaded it

**Comment by fschreyer** [comment]
Maybe run the buildlibrary on remind2 now and check whether some summations fail.

**Comment by pfuehrlich-pik** [comment]
I'm working on the test right now and create a PR later. The test is disabled in the version that is currently on master.
