### ISSUE TITLE
Add new price variables to the reporting

### ISSUE THREAD

**Issue by giannou** [pik-piam/remind2#120]
The remind2 task force issues list contains one with description:

"introduce mixed prices for liquids/gases etc. Price\|Final Energy\|Liquids, currently only Price\|Final Energy\|Liquids\|Biomass/Hydrogen/Fossil."

What variables are needed exactly? Is it maybe 
`Price|Secondary Energy|Gases`
`Price|Secondary Energy|Liquids`
..etc
or 
`Price|Final Energy|Gases`
`Price|Final Energy|Liquids`
..etc

or both?

**Comment by fschreyer** [comment]
Sry, that was wrong in the notes. It refers only to SE Prices, so

```
Price|Secondary Energy|Gases
Price|Secondary Energy|Liquids
Price|Secondary Energy|Solids
```
