### ISSUE TITLE
reportFE takes a long time and gives warnings

### ISSUE THREAD

**Issue by rauner** [pik-piam/remind2#138]
reportFE instead of taking a couple of secs now takes a couple of minutes and gives warnings. Seems to be related to the recent UE|Buildings changes:

Warning messages:
1: In .dimextract(x, k, 3, pmatch = pmatch, invert = invert) :
  Your dimnames in dim=3 contain duplicates! This might lead to erronous results and bad code performance. Please try to avoid duplicates in dimnames under all circumstances!
2: In .dimextract(x, k, 3, pmatch = pmatch, invert = invert) :
  Your dimnames in dim=3 contain duplicates! This might lead to erronous results and bad code performance. Please try to avoid duplicates in dimnames under all circumstances!
3: In .dimextract(x, k, 3, pmatch = pmatch, invert = invert) :
  Your dimnames in dim=3 contain duplicates! This might lead to erronous results and bad code performance. Please try to avoid duplicates in dimnames under all circumstances!
4: In .dimextract(x, k, 3, pmatch = pmatch, invert = invert) :
  Your dimnames in dim=3 contain duplicates! This might lead to erronous results and bad code performance. Please try to avoid duplicates in dimnames under all circumstances!
5: In .dimextract(x, k, 3, pmatch = pmatch, invert = invert) :
  Your dimnames in dim=3 contain duplicates! This might lead to erronous results and bad code performance. Please try to avoid duplicates in dimnames under all circumstances!
6: In .dimextract(x, k, 3, pmatch = pmatch, invert = invert) :
  Your dimnames in dim=3 contain duplicates! This might lead to erronous results and bad code performance. Please try to avoid duplicates in dimnames under all circumstances!

**Comment by rkrekeler** [comment]
Thanks @rauner for the heads up. #139 should fix this.
