### ISSUE TITLE
Deeper TOC in compareScenarios2() HTML Output?

### ISSUE THREAD

**Issue by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [pik-piam/remind2#167]
https://github.com/pik-piam/remind2/blob/bab3a9219300f08e1edd33909eaaa5c84fc5743f/inst/markdown/compareScenarios2/cs2_main.Rmd#L9-L12
Would there be a drawback to increase the TOC depth to six for the HTML output?  The TOC is collapsing anyway and it might increase "manoeuvrability" within the 400 (?) plots.

**Comment by chroetz** [comment]
I don't see a problem with that. We can change it to 6
