### ISSUE TITLE
cs2_plot_functions should be moved to the package proper

### ISSUE THREAD

**Issue by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [pik-piam/remind2#168]
With `cs2_plot_function.R` as a script in a separate file, it is a hassle to infer the parameters of the functions.  Moving them to the package proper will allow for man pages and example plots, which would be quite useful.  For example, I wasn't able to infer from 
https://github.com/pik-piam/remind2/blob/bab3a9219300f08e1edd33909eaaa5c84fc5743f/inst/markdown/compareScenarios2/cs2_plot_functions.R#L217-L221
that the resulting plot would/should look like this
![image](https://user-images.githubusercontent.com/53254462/150949598-36619698-c5a0-4989-9cb3-b66568b04cc2.png)

**Comment by chroetz** [comment]
I agree. I am currently working on moving these plot functions to the mip package

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
kk
