### ISSUE TITLE
Cyclic imports

### ISSUE THREAD

**Issue by chroetz** [pik-piam/remind2#181]
I want to use [`remind2::deletePlus()`](https://github.com/pik-piam/remind2/blob/83b71d0847499acb9bbc1cc7f50cf90bc3f3af1c/R/deletePlus.R#L27) in a function of the `mip` package (in [mip PR#27](https://github.com/pik-piam/mip/pull/27) in showAreaAndBarPlotsPlus.R). But `remind2` [imports](https://github.com/pik-piam/remind2/blob/83b71d0847499acb9bbc1cc7f50cf90bc3f3af1c/DESCRIPTION#L30) `mip`. So, `mip` cannot import `remind2`. How should this be resolved?

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
Move `deletePlus()` to `mip`, which is imported by `remind2`, so the function will be available there.

**Comment by chroetz** [comment]
Ah yes, that would work! 
But `deletePlus()` handles variable names created in the `remind2` report functions and the purpose of `mip` is visualization. So, it would strange to put `deletePlus()` into `mip`. 
I think, I prefer @fbenke-pik's suggestion of a separate utility package. Although this would only make sense if there is more than one function in it ;-)

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
I see, you don't do "easy" `:p`

**Comment by orichters** [comment]
done with piamutils::deletePlus()
