### ISSUE TITLE
cs2: missing linebreaks in PDF output for level 4 subsections

### ISSUE THREAD

**Issue by chroetz** [pik-piam/remind2#185]
![bad_arrangement](https://user-images.githubusercontent.com/69958015/152157546-5d0844d0-4f4b-46e2-b941-57df35012875.png)
There is no line break after a heading of a level 4 subsection and the following plot is placed after the heading to the right. Thus, the right part of the plot cannot be seen.

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
Seems I can't force a newline after a manual heading in the PDF.  Will unroll the loop … :disappointed:

**Comment by chroetz** [comment]
wait! I found a solution
