### ISSUE TITLE
Scenario Comparison 2 does not work with two runs with the same scenario name

### ISSUE THREAD

**Issue by Renato-Rodrigues** [pik-piam/remind2#195]
How to reproduce the issue: run compareScenarios2, select any group of runs with duplicated names. See the plots in the pdf merging the run results from two different runs in the same plot line. 

Expected behavior. The "old" compareScenarios added a suffix to any duplicated scenario name to avoid the problem, ex: "DIAG-NetZero" and "DIAG-NetZero_2" results were plotted in independent lines.

Ex: I selected two different DIAG-NetZero scenarios but both scenarios are merged in the plot lines:
![image](https://user-images.githubusercontent.com/33692508/155530618-84b1b159-fbe8-44b9-8a2b-5aae3fb9a017.png)

**Comment by chroetz** [comment]
As a workaround, you can rename scenarios in the cs2 function. If you have two scenarios both named "scen" with mifs located at "path1/to/scen.mif" and "path2/to/scen.mif" respectively, you can rename them to "scen_abc" and "scen_xyz", respectively, as follows:
```
compareScenarios2(
  mifScen = c("scen_abc" = "path1/to/scen.mif", "scen_xyz" = "path2/to/scen.mif"),
  mifHist = "path/to/historical.mif")
```
I wonder whether this actually is the better solution, as for automatically adding a suffix "_1" or "_2", you do not know which one is which. So explicitly renaming them should be preferred. 
Nonetheless, cs2 should at least give you a warning. And maybe, the warning message could state that you can do what I described above. 
@Renato-Rodrigues : Should cs2 abort if it detects duplicated scenario names to allow the user to directly specify the name or should it just add a default suffix like "_1" and "_2"?

**Comment by Renato-Rodrigues** [comment]
Hi Christof, thks for the fast reply!

From my point of view, calling by hand compareScenarios defeats the purpose of having an automated Rscript output.R to speed up our process.
Also, renaming the scenarios explicitly is not a solution as it would require continuous renaming whenever we want to run a comparison with more up to date data or newer model versions.

Knowing which runs the suffix referred to was never a problem before for us as they always followed the same order you chose when calling the compareScenarios function. Besides, adding the suffix was the way it always worked, and clearly merging the data together is not the right way to handle that. I am also against just disconsidering the duplicated scenario names as this defeats the purpose of the scenarios that you want to compare. 

If you are worried of having an explicit reference between the "renamed" scenarios and the original ones, you can simply add a reference table to the end of the scenarios comparison pdf relating the renamed scenarios and the path for the original runs. This is actually highly desirable to have as it would make easier to share results including the path for the actual runs.

So, my request would be to add the suffix as it was done before and, if possible, add the reference table to the end of the report.

**Comment by chroetz** [comment]
I like the idea of the reference table! 
I will implemented as you described, i.e., automatically adding the suffix and a reference table

**Comment by orichters** [comment]
I think it would be worth to always add a reference table with the short label and the folder name that generated the plot.

By the way: I already thought about adding a `description` field in the scenario config files where you can explain what this scenario does. This could also be added there somewhere, so you can remember it after a while.

Thanks, @chroetz, for fixing that…
