### ISSUE TITLE
Compare Scenarios function error related with IEA WEO 2021 data

### ISSUE THREAD

**Issue by Renato-Rodrigues** [pik-piam/remind2#196]
```
Error in .dimextract(x, k, 3, pmatch = pmatch) : 
  subscript out of bounds ("IEA WEO 2021 APS GLO", "IEA WEO 2021 Net2050 GLO", "IEA WEO 2021 SDS GLO", "IEA WEO 2021 SPS GLO")
```

Probably related with this line:
https://github.com/pik-piam/remind2/blob/2e21e641c4678628e2cdfd01c7d14d44a9729fe4/R/compareScenarios.R#L247

Reproduction: run Rscript output.R > select compareScenarios with recent runs from this folder: 

error report: /p/projects/remind/users/renatoro/ECEMF/v02_2022_02_23/compScen-prev-2022-02-24_14.20.23-EU27.err

**Comment by fbenke-pik** [comment]
I am removing this section, since it is no longer needed due to https://github.com/pik-piam/mrremind/pull/205

**Comment by fbenke-pik** [comment]
PR 197 has been merged. Should be fixed
