### ISSUE TITLE
support scenarios with the same name in compareScenarios2()

### ISSUE THREAD

**Issue by pweigmann** [pik-piam/remind2#207]
Feeding the current cs2 with runs that share the same scenario name (but different time-stamps) gives funny results:
![image](https://user-images.githubusercontent.com/28896133/156781655-38cfb477-5a72-476b-84e5-fa3c2b82d038.png)

Having two "Base" runs seems to add the data of both to a single scenario in this case. Would it be possible to support an automatic renaming, maybe in a similar way it was implemented in the old cs [here](https://github.com/pik-piam/remind2/blob/389d180146756928fc3d936c8596877634486009/R/compareScenarios.R#L165)?

**Comment by chroetz** [comment]
Does this still happen with the newest version? I hoped to have fixed this with #199 (with a change in the renaming in #205), after it was mentioned in #195.

**Comment by pweigmann** [comment]
Thanks for the reply, tested it again today using version 1.82 and it still happens.

**Comment by chroetz** [comment]
I introduced a bug in #205 :(
Will fix it.
