### ISSUE TITLE
New CES Calibration Reporting

### ISSUE THREAD

**Issue by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [pik-piam/remind2#253]
I'm going to overhaul the reporting for the CES calibration.  I'm feeling we are not getting the information we need from the current file and there might be information we don't look at at all.

So let's start with a "wish list" of what we want from the CES calibration reporting.
- [x] Proper display of deviations from the validation target
  - There is some working code for a heat-map table, based on @Renato-Rodrigues' Excel work.
- [x] Clear display of the progression of quantities and prices over the CES iterations.
  - The current display is not very readable with badly chosen colours.
- [ ] Filtering of quantities that do not have a calibration target (like energy intermediate production factors).
- [x] Display of absolute values of efficiency parameters, mentioned by @robertpietzcker.
- [x] Regions in alphabetic order.
- [ ] Production factors in some order resembling the CES tree.
- [x] automatically detect abnormal behaviors such as price spikes or divergent behaviors (and print these are warnings at the top)

Further questions:
- [ ] The current CES calibration reporting includes a section showing `vm_deltaCap` for selected technologies.  Is anybody using this?

**Comment by cchrisgong** [comment]
Thanks for this! I definitely find the color scheme... challenging.
May I also suggest some way to automatically detect abnormal behaviors such as price spikes or divergent behaviors (and print these are warnings at the top)? I am always in fear of overlooking something when I try to look at the graphs, and it is probably more efficient

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
> May I also suggest some way to automatically detect abnormal behaviors such as price spikes or divergent behaviors (and print these are warnings at the top)? 

Sure.  If you code it, we include it.

**Comment by johanneskoch94** [comment]
Thanks for this Michaja. In this context, maybe some of you may find the following "CES tree explorer" tool useful. It's a shiny app that you can run locally, with `remotes::install_github("johanneskoch94/myUtils")` and `myUtils::explore_CEStree("path(s)_to_my_gdxs")`. You can check all the ces tree parameters and factor levels, interactively. (It uses as "run" name, the name of the folder...). The sankey tab creates a sankey plot, but is still in development - you need to maximize the shiny app window, to be able to discern anything. 

![image](https://user-images.githubusercontent.com/43963181/167587139-fef7a185-8eb9-4ac0-b444-0f5fcb664063.png)
