### ISSUE TITLE
collect gdx files for better testing

### ISSUE THREAD

**Issue by orichters** [pik-piam/remind2#264]
Dear colleagues,

[test-convGDX2mif](https://github.com/pik-piam/remind2/blob/master/tests/testthat/test-convGDX2mif.R#L52:L53) allows to further specify GDX files to be tested. Can we specify a folder on the cluster and collect some `fulldata-whatever.gdx` files there from a coupled run, a EU21 run, a default run, a run with sector-differentiated carbon-prices etc.?

Then, we can add a short script there as a comment that collects all these files, so if you want to test all gdxes to be safe for a bigger change, you quickly uncomment the script (without making it the default of course)?

Where on the cluster could that be? I can probably do the rest myself.

Maybe something like `/p/projects/remind/debugging/gdx-examples`?

**Comment by Renato-Rodrigues** [comment]
Maybe you could use the gdx files from the different remind calibrations as a starting point.
/p/projects/remind/inputdata/CESparametersAndGDX

**Comment by orichters** [comment]
`/p/projects/remind/modeltests/output/*/fulldata.gdx` are also candidates

**Comment by orichters** [comment]
Done with #272
