### ISSUE TITLE
Variable name wrong?

### ISSUE THREAD

**Issue by giannou** [pik-piam/remind2#3]
https://github.com/pik-piam/remind2/blob/433b7687b7eda43adc8dcdd0f6e11c9209a92eac/R/reportFE.R#L755

Shouldn't the name of the total read `FE|Transport|Pass|ESD (EJ/yr)` instead of `FE|Transport|ESD|Pass (EJ/yr)` ?
Came across the issue while completing the summation checks based on the "+" in the variable names.

**Comment by Loisel** [comment]
I think @Renato-Rodrigues introduced all the ESD variables, but judging from the other variables I fully agree.

**Comment by Renato-Rodrigues** [comment]
Yes, it is definitely a mistype from my part. Thank you for catching it. I will fix it asap.

**Comment by Renato-Rodrigues** [comment]
fixed in commit https://github.com/pik-piam/remind2/commit/c45abce3c6656bcdc09332fd3fd5c10b77e6e9ec
