### ISSUE TITLE
Harmonize y-axes in compScen?

### ISSUE THREAD

**Issue by orichters** [pik-piam/remind2#352]
Is it possible to harmonize the y-axis in these compareScenario plots? I think this would improve the readability of these comparisons a lot. Asking @chroetz and @pweigmann, do you have an idea?

![image](https://user-images.githubusercontent.com/90761609/203014298-54395c07-c23c-4dd2-8066-745341abf8a6.png)

**Comment by chroetz** [comment]
At the moment the "free" scales are hard-coded. One can change that by making [this](https://github.com/pik-piam/mip/blob/275eadbc1a948d5220fe92d46f53dd94184f5b9a/R/showAreaAndBarPlots.R#L141) `scales` value an argument of `showAreaAndBarPlots()`. Then you could choose [here](https://github.com/pik-piam/remind2/blob/83de00e7787adde22c81827626d3050dc338a3a0/inst/markdown/compareScenarios2/cs2_01_summary.Rmd#L245) how the plots should be displayed.
