### ISSUE TITLE
compareScenarios2() doesn't flush pages on new section

### ISSUE THREAD

**Issue by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [pik-piam/remind2#370]
`compareScenarios2()` doesn't flush pages on new section, occasionally piling up empty sections' headers and clipping plots, e.g.
![image](https://user-images.githubusercontent.com/53254462/211288347-e6decabf-6c12-4baf-912b-3645d04f6194.png)

**Comment by orichters** [comment]
Noticed that as well working with cs2, but couldn't find a solution that did not create many blank pages. Decided to "fix" that with some strategically placed `\newline` statements, see [`inst/markdown/compareScenarios2/cs2_08_sdp.Rmd`](https://github.com/pik-piam/remind2/pull/354/files#diff-3b622e5318f00efa33c22ee1945ed183d6a651cd3e0a894762dff6d6fb834390R58).

**Comment by fbenke-pik** [comment]
I agree with Oliver. I am aware of the problem, but cannot think of any other solution that inserting `\ņewpage` commands whenever you start a new subsection. There does not seem to be a way to instruct the renderer to automatically introduce page breaks for an level1/2/3 section.

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
> There does not seem to be a way to instruct the renderer to automatically introduce page breaks for level1/2/3/.. sections.

But we can force one before every code chunk, which is basically the same.
````Rmd
---
output:
  pdf_document: default
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, pageflush = TRUE)
knitr::knit_hooks$set(
    pageflush = function(before, options, envir, name, ...) {
    if (before && isTRUE(options$pageflush)) {
        return('\\clearpage')
    }
})
```
# Test

## Foo
```{r foo}
hist(rnorm(100))
```

## Bar
```{r bar, pageflush = FALSE}
hist(rnorm(100))
```
````
![image](https://github.com/user-attachments/assets/1acdb089-5139-4451-8822-ed1a25cbe82d)

**Comment by fbenke-pik** [comment]
This is what your proposed solution would look like for a sample section: https://cloud.pik-potsdam.de/index.php/f/22084276

Probably too many page breaks, if you ask me. On the other hand, rather unnecessary page breaks than truncated plots...

**Comment by fbenke-pik** [comment]
I would look into why the rendered plot is truncated instead and if we can make ggplot adjustments that will cause the plot to be moved to a new page if there is not enough space on the page left. I can have a look, but would need a suitable example (mif file and name of the affected plot)  to reproduce the problem.
