### ISSUE TITLE
reading p47_taxCO2eq_AggFE regardless of module realisation causes warning messages

### ISSUE THREAD

**Issue by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [pik-piam/remind2#390]
https://github.com/pik-piam/remind2/blob/0daa409f0c0e009f9787f71f206e9d1e5aaa4356/R/reportLCOE.R#L116

**Comment by orichters** [comment]
fixed in https://github.com/pik-piam/remind2/pull/412
