### ISSUE TITLE
variables with unit NA

### ISSUE THREAD

**Issue by orichters** [pik-piam/remind2#408]
Warning (test-convGDX2mif.R:120:5): Test if REMIND reporting is produced as it should and check data integrity These variables and units contain NA:
- Services and Products|Transport|non-LDV|Sales|apCarDiT (NA)
- Services and Products|Transport|non-LDV|Sales|apcarDiEffH2T (NA)
- Services and Products|Transport|non-LDV|Sales|apcarDiEffT (NA)
- Services and Products|Transport|non-LDV|Sales|uedit (NA)
- Services and Products|Transport|non-LDV|Stock|apCarDiT (NA)
- Services and Products|Transport|non-LDV|Stock|apcarDiEffH2T (NA)
- Services and Products|Transport|non-LDV|Stock|apcarDiEffT (NA)
- Services and Products|Transport|non-LDV|Stock|uedit (NA)

**Comment by robertpietzcker** [comment]
sorry for not reacting to the messages earlier. 
Is it a problem if they are NA? non-LDV is a variable that is very hard to put into a useful unit....

**Comment by orichters** [comment]
Those specific variables are now ignored.
