### ISSUE TITLE
Cleanup FE Prices in cs2

### ISSUE THREAD

**Issue by orichters** [pik-piam/remind2#418]
After adding FE price variables in https://github.com/pik-piam/remind2/pull/402 and fixing the bug that omitted all Energy prices in https://github.com/pik-piam/remind2/pull/417, these [`walk` calls for FE Prices](https://github.com/pik-piam/remind2/blob/master/inst/markdown/compareScenarios2/cs2_02_macro.Rmd#L168-L194) in `cs2_02_macro.Rmd` of compareScenarios2 create way too many plots. It was 18 pages in January, now it is > 200. I would appreciate if you could replace this code to select the variables you actually look at. Maybe @fschreyer, @Renato-Rodrigues?

**Comment by fschreyer** [comment]
I think we don't need the line plots and bar plots for the distinction of FE Prices in  ``Total LCOE``, ``Fuel Cost``, ``Transport and Distribution``, ``Carbon Price Component``, ``Other Taxes``. They can be all removed. If somebody wants to know about it, they can work based on the mif files.
