### ISSUE TITLE
`Secondary Energy|Electricity|Share of renewables in gross demand|Estimation`

### ISSUE THREAD

**Issue by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [pik-piam/remind2#425]
> It might arise from a mistaken understanding of "gross demand" that I had some years ago, namely that it was more connected to the final energy demand. In fact, "gross electricity demand" is just the sum of electricity generation plus imports (excluding output from pump hydro storage that has no natural inflows).
> 
> accordingly, the best approximation for "Secondary Energy|Electricity|Share of renewables in gross demand|Estimation" would be
> ```R
>   100 
> * ( output[,,"SE|Electricity|Non-Biomass Renewables (EJ/yr)"] 
>   + output[,,"SE|Electricity|Biomass (EJ/yr)"]
>   )
> / ( output[,,"SE|Electricity (EJ/yr)"]
>   + output[,,"SE|Electricity|Net Imports (EJ/yr)"]
>   )
> ```

[[↑]](https://github.com/pik-piam/remind2/issues/420#issuecomment-1618390468)

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
@robertpietzcker 
That will not work, as `SE|Electricity|Net Imports` is not available for all realisations of the `trade` module.
https://github.com/pik-piam/remind2/blob/cafb0ddd1999c63a12fb9e4c771c4ee9f521a6e1/R/reportSE.R#L350-L365

**Comment by robertpietzcker** [comment]
Ok. 

I know very little R magic, so a simple question, @0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q  
Would it be possible to simply always report the variable `SE|Electricity|Net Imports`, and if there is no entry, set it to 0 (because if there is no variable in REMIND, then clearly imports were 0)?

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
Sure can do.
