### ISSUE TITLE
local caching of gdxes for tests?

### ISSUE THREAD

**Issue by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [pik-piam/remind2#468]
Downloading the same gdxes over and over and over for every test is getting on my nerves.  Especially if the download fails for some inexplicable reason.

Therefore I suggest to add some code to `test-convGDX2mif.R` that
- checks some local R setting (e.g. `options('test-convGDX2MIF_gdx_cache')`)
- if that returns `NULL`, download gdxes as it does now
- if that returns something else, interpret that as a path where gdxes are cached locally and use them instead
- but download a signature file from where the gdxes are now, with checksums for the gdxes, to fail if the gdxes are updated upstream and the cache is stale

I can implement that (apart from the signature file, since I am not sure where the gdxes are located).  I would just like to get some feedback by RSE whether this is OK to do or not.
@fbenke-pik?

**Comment by fbenke-pik** [comment]
Don't see any problems with that, so feel free to go ahead. I can help with placing the signature files on the RSE server (have access, but need instructions what needs to be done).

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
Can you run `$ md5sum * > checksums` in the directory the files are located in for final testing?

**Comment by fbenke-pik** [comment]
I ran the command. Let me know if you need sth else from me.

**Comment by dklein-pik** [comment]
Hi @0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q, why did you close this? @orichters suggests to use it [here](https://github.com/pik-piam/remind2/blob/0f8208173192bd05edf61ba5d1acade2cb06d698/tests/testthat/test-convGDX2mif.R#L25) since we download more gdx files now.
