### ISSUE TITLE
Improve cs2 climate plots of temperature & concentration distributions from MAGICC

### ISSUE THREAD

**Issue by orichters** [pik-piam/remind2#487]
At the moment, the section on "Climate" just shows line plots of global mean temperature and forcing.

With MAGICC 7.5.3, we will have access to the full distribution of climate outcomes, and I think it would be great to plot that. This concerns temperatures, effective radiative forcing and atmospheric concentrations.

As only `World` data is available and therefore no need to show regional results, I have something like this in mind: A line plot with all 50th percentile pathways, and for each scenario a plot which include the 50th percentile but then shows as distribution something like the 33th – 67th percentile in a darker color, and the 5th – 95th percentile in a lighter color, similar as in the mockup attached.

Ideally, one would have a new `mip` function that generates that where you can simply specify either the percentiles or the variables you want to use. We could add that to `piamInterfaces::plotIntercomparison` as well for model intercomparison.

I can provide some `R` code that Jarmo Kikstra from IIASA uses for his assessment, but it does not really fit into our mip standard, I suspect.

Here is data for testing --> [ngfs-magicc-data.xlsx](https://github.com/pik-piam/remind2/files/13424878/ngfs-magicc-data.xlsx)

I think it makes sense to use `Atmospheric Concentrations|CH4` instead of `AR6 climate diagnostics|Atmospheric Concentrations|CH4|MAGICCv7.5.3|50.0th Percentile` as a label, but let us see which variable names we will finally use internally.

![image](https://github.com/pik-piam/remind2/assets/90761609/7d2a651d-17cc-4117-b353-bc5fba9f4fea)

**Comment by gabriel-abrahao** [comment]
I like the suggestion. Keep in mind that the plan is that every REMIND run will still have a simple `Temperature|Global Mean` variable with a best estimate, and these `AR6 climate assessment` variables, which show the uncertainty range, should appear in the same mif but be optional, conditional on adding something to `cfg$output`. So this should be robust to the absence of the latter. We could make it default, but I think it's best not to add ~12m of runtime to the reporting unless someone really needs it.
