### ISSUE TITLE
Add structure for range checks

### ISSUE THREAD

**Issue by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [pik-piam/remind2#526]
Should be possible to test stuff like `Emi|CO2|Energy|Demand|Industry|Chemicals|Solids|+|Fossil > 0`.

FYI @fbenke-pik.

**Comment by pweigmann** [comment]
Not sure what the exact application would be, but sounds like something that could potentially be done within the [validation tool scope](https://github.com/remindmodel/development_issues/issues/235)?

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
If you want trivial checks like "fossil emissions cannot be negative" in there, be my guest.  As long as it is fast.

**Comment by pweigmann** [comment]
Not necessarily. In which way should it be more than ``all(data[, , "var"] > 0)`` for a list of variables? What would be the desired input, output?

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
Basically the same as https://github.com/pik-piam/remind2/blob/af6b2f59cc143343dd9acd10cdfb8fac8782bc45/R/convGDX2MIF.R#L139-L148 but checking ranges instead of sums.
Stuff not being negative, and shares not exceeding 100 % (especially globally if they are simply summed up) comes to mind.

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
> Basically the same as …

but it should break the tests.  If variables that should not turn negative do turn negative, whatever was changed on the reporting was wrong.

**Comment by fbenke-pik** [comment]
In general, I can add basic functions to piamInterfaces for basic range checks (e.g. value > 0, sums up to 100).  They then called as part of the convGDX2Mif test in remind2. 

We would have to revisit this once Pascal has finished implementation of the validation tool to avoid redundancies. 

Will bring this up to discuss with Pascal during next RSE meeting. 

@orichters Any thoughts on your end?

**Comment by orichters** [comment]
I wouldn't do that. Pascal is working on getting the validation tool ready which should do exactly these kind of tests. If you have time to spare, you could start populating the online file with the conditions you have in mind so it quickly becomes a useful tool.
