### ISSUE TITLE
CS2 Industry with Industrial Processes plot broken

### ISSUE THREAD

**Issue by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [pik-piam/remind2#527]
3.4.12 Industry with Industrial Processes (page 181) in the compScen pdf.
```
## Error in mipLineHistorical(., x_hist = dRegiHist, ylab = NULL, scales = scales, : Number of provided colors for historical data (#6) does not match number
```
https://github.com/pik-piam/remind2/blob/af6b2f59cc143343dd9acd10cdfb8fac8782bc45/inst/markdown/compareScenarios2/cs2_03_emissions.Rmd#L192-L210

I do not have a revision range for this, but it did work on 4 December and did not on 6 December, which should have been before `v1.124.0`.

Assigning @fbenke-pik in order to not assign no one and have this fall through the cracks.

**Comment by fbenke-pik** [comment]
Unifying legends fails because the additional calculations in the respective chunks introduce all-NA values for certain reference sources. This crashes in showLinePlots, as it assumes that all NA values have been removed in cs2_main.

**Comment by fbenke-pik** [comment]
Michaja, please check again when you find time and reopen if the problem persists.
