### ISSUE TITLE
CS2 2.11.5 FE|Transport Prices plot broken

### ISSUE THREAD

**Issue by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [pik-piam/remind2#529]
https://github.com/pik-piam/remind2/blob/af6b2f59cc143343dd9acd10cdfb8fac8782bc45/inst/markdown/compareScenarios2/cs2_02_macro.Rmd#L191-L196
```
## Error in carrierslevels(dPrice$variable): could not find function "carrierslevels"
```

**Comment by orichters** [comment]
Sorry, definitely my fault. Maybe the cs2 test should actually test whether cs2 runs without error. Fixed in https://github.com/pik-piam/remind2/pull/521/files#diff-6e79b51a6777f091c3e21cf942e3e0b6d8a3f9b9f0f649cf0a7ba7eafdecf573
