### ISSUE TITLE
this duplicate entry breaks coupled runs

### ISSUE THREAD

**Issue by giannou** [pik-piam/remind2#55]
https://github.com/pik-piam/remind2/blob/25f67ab60d28a98fbcee4f926660d46e82fe0337/R/reportFE.R#L208

found also here:
https://github.com/pik-piam/remind2/blob/25f67ab60d28a98fbcee4f926660d46e82fe0337/R/reportFE.R#L805

@fschreyer can you please fix?

**Comment by giannou** [comment]
there might be also more duplicates of the same kind

**Comment by fschreyer** [comment]
I think, this part was done by @Renato-Rodrigues

**Comment by giannou** [comment]
the most recent change is by you though

**Comment by fschreyer** [comment]
well, ok...you got me ;-). I can do it. Are there any other duplicates of this kind? Can you quickly check?
