### ISSUE TITLE
Too low sectoral FE prices reported?

### ISSUE THREAD

**Issue by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [pik-piam/remind2#576]
https://github.com/pik-piam/remind2/blob/49ece8d4b39afca439bbc9e9343ce7c85ffe14e7/R/reportCosts.R#L407-L409

1. `price_fe_indst_emiMkt` is `q37_demFeIndst.m(entyFe,emiMkt)` over `qm_budget.m`, so has dimensions [`entyFe`, `emiMkt`]
2. `quant_fe_indst_emiMkt` is `vm_demFeSector.l(entySe,entyFe,"indst",emiMkt)`, summed over `entySe` and `sector`, so has dimensions [`entyFe`, `emiMkt`]
3. `price_fe_indst` should be the average of FE prices, weighted over emissions markets, but
   - numerator is `price_fe_indst_emiMkt * quant_fe_indst_emiMkt`, summed over `emiMkt`, so has dimension [`entyFe`] :heavy_check_mark: 
   - denominator is `price_fe_indst_emiMkt`, summed over `entyFe` and `emiMkt`, so has dimension [1] :heavy_multiplication_x:
   So FE prices are not weighted by FE demand by emission market, but by demand of all FE.

Minimal Example:
```
library(tidyverse)
library(magclass)

d <- tribble(
  ~entyFe,   ~emiMkt,   ~price,   ~quantity,
  'fesos',   'ETS',     1,        10,
  'fesos',   'ES',      2,        10,
  'feels',   'ETS',     3,        20,
  'feels',   'ES',      4,        10)

price <- as.magpie(select(d, entyFe, emiMkt, price), 
                   spatial = 0, temporal = 0, datacol = 3)

quant <- as.magpie(select(d, entyFe, emiMkt, quantity), 
                   spatial = 0, temporal = 0, datacol = 3)
```
I would expect to be the prices for `fesos` and `feels` to be the average prices across emission sectors, so between 1 and 2 for `fesos` ((1 × 10 + 2 × 10) ÷ 20 = 1.5) and between 3 and four for `feels` ((3 × 20 + 4 × 10) ÷ 30 = 3.333).
```
dimSums(price * quant, dim = 3.2) / dimSums(quant, dim = 3.2)
```
```
An object of class "magpie"
, , entyFe = fesos

      d2
region [,1]
   GLO  1.5

, , entyFe = feels

      d2
region     [,1]
   GLO 3.333333
```
But the calculation in `reportCosts()` gives
```
dimSums(price * quant, dim = 3.2) / dimSums(quant, dim = 3)
```
```
An object of class "magpie"
, , entyFe = fesos

      d2
region [,1]
   GLO  0.6

, , entyFe = feels

      d2
region [,1]
   GLO    2
```
Or am I missing something?

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
FYI @robinhasse affects buildings just the same https://github.com/pik-piam/remind2/blob/49ece8d4b39afca439bbc9e9343ce7c85ffe14e7/R/reportCosts.R#L411-L413

**Comment by Renato-Rodrigues** [comment]
This code is pre REMIND-EU merge. 
I am not sure what is being used for, but I would say that it would be much better if it used the prices calculated in the reportPrices instead.
I never worked with the cost reporting although, so I cannot say much about this code.

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
No, it is from the REMIND-EU merge.
I agree on the `reportPrices()` part, though.

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
@amerfort, @katarkow, @tabeado (not sure who "owns" the CDR module): be advised that  `Energy costs CDR` were reported too low because of this.
