### ISSUE TITLE
Wrong Reporting of Industry Emissions due to Dimensionality Reduction when Reading Magclass Object

### ISSUE THREAD

**Issue by fschreyer** [pik-piam/remind2#584]
Hi Oli and Falk,

@orichters @fbenke-pik 

I noticed that industry emissions are not reported correctly in my latest runs (``/p/projects/ariadne/remind/output/NPi_2024-04-04_10.08.36``). Specifically, ``Emi|CO2|Industrial Processes|+|Chemicals`` is zero everywhere and ``Emi|CO2|Energy|Demand|+|Industry`` is too high. I could not spot this issue in the latest AMTs, though, as there have not been any for the past weeks. Not sure where exactly it was introduced. The issue goes back to [this line](https://github.com/pik-piam/remind2/blob/0f8208173192bd05edf61ba5d1acade2cb06d698/R/reportEmi.R#L150) which makes ``vm_demFENonEnergySector`` zero everywhere after applying the function ``matchDim()``. The line was introduced in [this commit](https://github.com/pik-piam/remind2/commit/c5a644e012f0cb52b33fe61c598183777389f329) and the function itself was introduced earlier by Falk. I think, this was done somehow in the process of moving to ``restore_zero=F`` in all ``readGDX`` functions to save memory but it seems to introduce a bug here. 

Can somebody of you have a look?

**Comment by orichters** [comment]
Don't really know why this commit is stated as source of the change, it actually was introduced [here](https://github.com/pik-piam/remind2/pull/563/files#diff-0c2c1bfb6bf4b90bf16c9de64f770cf319e35c2683196b8bafbf1c04fd6b6ac4), maybe created by a merge? So I hope Falk can clarify what might cause this.

**Comment by orichters** [comment]
I just checked and for my recent NGFS runs using the latest `remind2` version (`/p/tmp/oliverr/NGFS_v5/remind-2024-03-27/output/C_h_cpol-rem-3`), `Emi|CO2|Industrial Processes|+|Chemicals` is not zero everywhere. Are we sure this is actually the problem here?

**Comment by fschreyer** [comment]
Yeah, it seems to be only with certain GDXs. For my example GDX

```
  # FE non-energy use
  vm_demFENonEnergySector <- readGDX(gdx, "vm_demFENonEnergySector", field = "l",
                                     restore_zeros = F, react = "silent")[,t,]
 ```
 
 yields an object with only 3 subdimensions in the third dimension, removing the emissions market dimension which is present in ``vm_demFeSector``. With a GDX from the release runs, for example, it keeps this 4th dimension because there are non-zero values for the ``ES`` in this GDX.

**Comment by fbenke-pik** [comment]
> yields an object with only 3 subdimensions in the third dimension, removing the emissions market dimension which is present in `vm_demFeSector`. With a GDX from the release runs, for example, it keeps this 4th dimension because there are non-zero values for the `ES` in this GDX. Then `vm_demFENonEnergySector`and `vm_demFeSector` do not have the same dimensions anymore.

This should not be the problem. We created `matchDim` to bring back the dimension and fill it with zeros in this line
`    vm_demFENonEnergySector <- matchDim(vm_demFENonEnergySector, vm_demFeSector)`

**Comment by fbenke-pik** [comment]
Found the problem. As before, the solution is to avoid dumb guessing by magclass by setting the spatial argument when reading the gdx. I am preparing a PR.

**Comment by fschreyer** [comment]
It is fixed. My mif files now contain correct emissions. For instance,  ``/p/projects/ariadne/remind/output/NPi_2024-04-04_10.08.36``. Thanks!
