### ISSUE TITLE
make compareScenarios compatible with differing scenario structures

### ISSUE THREAD

**Issue by giannou** [pik-piam/remind2#63]
context:
add to compScen a function that fills all missing variables with N/A to allow comparison of two different runs that have different numbers of reporting variables.
this will become more relevant when we switch between simple and complex modules, where sometimes it really doesn't make sense to try to fill in variables for the simple module realization

**Comment by chroetz** [comment]
`compareScenarios2()` can deal with partially missing variables. As it is the new standard, I close this issue.
