### ISSUE TITLE
Move compareScenarios to own Repo

### ISSUE THREAD

**Issue by Loisel** [pik-piam/remind2#7]
It might be advised to move `compareScenarios` to it's own repo, it
- has a quite distinct purpose
- takes (equally) long to test, so `remind2` tests would be much faster if we do not include `compareScenarios`.

**Comment by Renato-Rodrigues** [comment]
I am not sure I agree. 
remind2 library goal is to include REMIND results reporting code.
The compareScenarios is a REMIND reporting function. Therefore I think it belongs perfectly to this library.
Moreover, if you split it to another library, it increases the probability of changes in variable names in the remind2 library not being considered properly in the compareScenarios function.

**Comment by LaviniaBaumstark** [comment]
I agree to Renato. I would keep compareScenarios in he remind2 package to have only one place to be checked if a reporting variable is renamed.

**Comment by Loisel** [comment]
I see the point. On the other hand, testing `compareScenarios` takes approx 6 minutes. I'd say 8mins is still ok as a build time (+ 2 minutes for convGDX2mif), but we had quite some discussion on the runtime of builds. Ok so I'll close this.
