### ISSUE TITLE
Values swapped between scenarios due to partly repeated names

### ISSUE THREAD

**Issue by giannou** [pik-piam/remind2#89]
This code chunk seems to contain a bug: https://github.com/pik-piam/remind2/blob/c6380a4260a4c9fdae8afd68945e4df9da6305d6/R/compareScenarios.R#L165

When comparing 3 scenarios, 2 of which have identical scenario names, values are exchanged between the unique scenario and one of the two repeated ones.

**Comment by cchrisgong** [comment]
Thanks for pointing this out. By values swapped, do you mean if the original scenarios are (A,A,B), you get A1, B1, A, instead of A1, A2, B?

**Comment by cchrisgong** [comment]
Thanks for pointing this out. Just to make sure, as an example, if the original scenarios are [A,B,A], it becomes A1, A2, B1, correct?

**Comment by giannou** [comment]
> Thanks for pointing this out. Just to make sure, as an example, if the original scenarios are [A,B,A], it becomes A1, A2, B1, correct?

yes

**Comment by giannou** [comment]
fixed with #90
